# Generated by Django 4.1.3 on 2022-11-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bio_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.ManyToManyField(related_name='countries', to='users.country'),
        ),
    ]
